version: '2'
services:
  mysql:
    image: mysql:latest
    container_name: MySQL
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: examazon
      MYSQL_USER: owner
      MYSQL_PASSWORD: owner